name: Destroy IaC API Whisper
on:
  workflow_dispatch:
    inputs:
      destroyType:
        type: choice
        description: 'Do you want to destroy (no or yes)?'     
        required: true
        default: 'no'
        options: ['no', 'yes']

permissions:
  contents: read

jobs:
  tf-destroy:
    name: Terraform destroy
    runs-on: ubuntu-latest
    env:
      environment: $GITHUB_REF_NAME
      TF_VAR_region: ${{ vars.REGION }}
      TF_VAR_whisper_ecr_repo: ${{ vars.WHISPER_ECR_REPO }}
      TF_VAR_image_tag: ${{ vars.IMAGE_TAG }}
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_subdomain_name: ${{ vars.API_DOMAIN_NAME }}
      TF_VAR_acm_certificate_arn: ${{ secrets.API_ACM_CERTIFICATE_ARN }}
      
    if: github.event.inputs.destroyType == 'yes'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Terraform Workflow
        working-directory: infrastructure/terraform/environments
        run: |
          cd ${{ env.environment }}/api-whisper
          terraform init
          terraform plan -destroy
          terraform destroy -auto-approve