name: Build Frontend For Whisper Service

on:
  push:
    branches: [ "dev" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    name: Build source and Synch to S3
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
      
    - name: Build source
      working-directory: frontend
      run: |
        npm ci    
        npm run build --if-present    

    - name: Check Result Build
      working-directory: frontend
      run: ls