name: Build Frontend For Whisper Service

on:
  push:
    branches: [ "dev" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    name: Build source and Synch to S3
    runs-on: ubuntu-latest
    env:
      S3_Bucket_Name: ${{ vars.S3_BUCKET_NAME }}

 
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.REGION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
      
    - name: Build source
      working-directory: frontend
      run: |
        npm ci    
        npm run build --if-present    

    - name: Check Result Build
      working-directory: frontend
      run: aws s3 cp build s3://$S3_Bucket_Name --recursive