name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.REGION }}
      WHISPER_ECR_REPO:  ${{ vars.WHISPER_ECR_REPO }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: api-whisper
      run: |
        docker images
        docker build $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$WHISPER_ECR_REPO .
        docker images